name: Build

on: 
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
      - uses: actions/setup-java@v4
        with:
          # AGP8 needs JDK 17
          distribution: 'temurin'
          java-version: '17'
      - name: Build
        uses: oberhauser-dev/flutter-release-action@v0
        with:
          token: ${{ github.token }}
          dry-run: true
          app-name: 'hotel_sunshine'
          app-version: ${{ github.ref_name }} # or set manually: 'v1.2.3-alpha.4'
          tag: ${{ github.ref }}
          build-type: 'apk'